-- MySQL Script generated by MySQL Workbench
-- jue 06 feb 2020 13:08:53 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persons` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `last_connection` VARCHAR(45) NULL,
  `num_articles_searched` INT NULL,
  `field` VARCHAR(45) NULL,
  `is_developer` TINYINT(1) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Journal` (
  `automatic_id_journal` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`automatic_id_journal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article` (
  `article_id` VARCHAR(45) NOT NULL,
  `title` VARCHAR(255) NULL,
  `abstract` TEXT(2000) NULL,
  `article_date` VARCHAR(45) NULL,
  `last_search_date` VARCHAR(45) NULL,
  `url` VARCHAR(255) NULL,
  `Journal_idJournal` INT NOT NULL,
  PRIMARY KEY (`article_id`, `Journal_idJournal`),
  INDEX `fk_Article_Journal1_idx` (`Journal_idJournal` ASC),
  CONSTRAINT `fk_Article_Journal1`
    FOREIGN KEY (`Journal_idJournal`)
    REFERENCES `mydb`.`Journal` (`automatic_id_journal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Article` (
  `User_iduser` INT NOT NULL,
  `Article_idArticle` INT NOT NULL,
  `is_author` TINYINT(1) NULL,
  `is_user` TINYINT(1) NULL,
  PRIMARY KEY (`User_iduser`, `Article_idArticle`),
  INDEX `fk_User_has_Article_Article1_idx` (`Article_idArticle` ASC),
  INDEX `fk_User_has_Article_User_idx` (`User_iduser` ASC),
  CONSTRAINT `fk_User_has_Article_User`
    FOREIGN KEY (`User_iduser`)
    REFERENCES `mydb`.`Persons` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Article_Article1`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `mydb`.`Article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metrics` (
  `idMetrics` INT NOT NULL,
  `pubmed_citations` VARCHAR(45) NULL,
  `wikipedia_references` VARCHAR(45) NULL,
  `scopus_citations` VARCHAR(45) NULL,
  `crossref_citations` VARCHAR(45) NULL,
  `mendeley_captures` VARCHAR(45) NULL,
  `num_tweets` VARCHAR(45) NULL,
  PRIMARY KEY (`idMetrics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Values` (
  `idValues` INT NOT NULL,
  `pubmed_citations` INT NULL,
  `wikipedia_references` INT NULL,
  `scopus_citations` INT NULL,
  `crossref_citations` INT NULL,
  `mendeley_captures` INT NULL,
  `num_tweets` INT NULL,
  `Metrics_idMetrics` INT NOT NULL,
  PRIMARY KEY (`idValues`, `Metrics_idMetrics`),
  INDEX `fk_Values_Metrics1_idx` (`Metrics_idMetrics` ASC),
  CONSTRAINT `fk_Values_Metrics1`
    FOREIGN KEY (`Metrics_idMetrics`)
    REFERENCES `mydb`.`Metrics` (`idMetrics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hashtags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hashtags` (
  `idHash` INT NOT NULL,
  `hashtags` VARCHAR(255) NULL,
  PRIMARY KEY (`idHash`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Field` (
  `idField` INT NOT NULL,
  PRIMARY KEY (`idField`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Web_Statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Web_Statistics` (
  `idWeb_Statistics` INT NOT NULL,
  `num_searches` VARCHAR(45) NULL,
  PRIMARY KEY (`idWeb_Statistics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hashtags_has_Metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hashtags_has_Metrics` (
  `Hashtags_idHash` INT NOT NULL,
  `Metrics_idMetrics` INT NOT NULL,
  PRIMARY KEY (`Hashtags_idHash`, `Metrics_idMetrics`),
  INDEX `fk_Hashtags_has_Metrics_Metrics1_idx` (`Metrics_idMetrics` ASC),
  INDEX `fk_Hashtags_has_Metrics_Hashtags1_idx` (`Hashtags_idHash` ASC),
  CONSTRAINT `fk_Hashtags_has_Metrics_Hashtags1`
    FOREIGN KEY (`Hashtags_idHash`)
    REFERENCES `mydb`.`Hashtags` (`idHash`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hashtags_has_Metrics_Metrics1`
    FOREIGN KEY (`Metrics_idMetrics`)
    REFERENCES `mydb`.`Metrics` (`idMetrics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article_has_Metrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article_has_Metrics` (
  `Article_doi` VARCHAR(45) NOT NULL,
  `Article_Journal_idJournal` INT NOT NULL,
  `Metrics_idMetrics` INT NOT NULL,
  PRIMARY KEY (`Article_doi`, `Article_Journal_idJournal`, `Metrics_idMetrics`),
  INDEX `fk_Article_has_Metrics_Metrics1_idx` (`Metrics_idMetrics` ASC),
  INDEX `fk_Article_has_Metrics_Article1_idx` (`Article_doi` ASC, `Article_Journal_idJournal` ASC),
  CONSTRAINT `fk_Article_has_Metrics_Article1`
    FOREIGN KEY (`Article_doi` , `Article_Journal_idJournal`)
    REFERENCES `mydb`.`Article` (`article_id` , `Journal_idJournal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_has_Metrics_Metrics1`
    FOREIGN KEY (`Metrics_idMetrics`)
    REFERENCES `mydb`.`Metrics` (`idMetrics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persons_has_Field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persons_has_Field` (
  `Persons_email` VARCHAR(45) NOT NULL,
  `Field_idField` INT NOT NULL,
  PRIMARY KEY (`Persons_email`, `Field_idField`),
  INDEX `fk_Persons_has_Field_Field1_idx` (`Field_idField` ASC),
  INDEX `fk_Persons_has_Field_Persons1_idx` (`Persons_email` ASC),
  CONSTRAINT `fk_Persons_has_Field_Persons1`
    FOREIGN KEY (`Persons_email`)
    REFERENCES `mydb`.`Persons` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persons_has_Field_Field1`
    FOREIGN KEY (`Field_idField`)
    REFERENCES `mydb`.`Field` (`idField`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Web_Values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Web_Values` (
  `idWeb_Values` INT NOT NULL,
  `Web_Statistics_idWeb_Statistics` INT NOT NULL,
  `num_searches` INT NULL,
  PRIMARY KEY (`idWeb_Values`),
  INDEX `fk_Web_Values_Web_Statistics1_idx` (`Web_Statistics_idWeb_Statistics` ASC),
  CONSTRAINT `fk_Web_Values_Web_Statistics1`
    FOREIGN KEY (`Web_Statistics_idWeb_Statistics`)
    REFERENCES `mydb`.`Web_Statistics` (`idWeb_Statistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keywords` (
  `idKeywords` INT NOT NULL,
  `keyword` VARCHAR(45) NULL,
  PRIMARY KEY (`idKeywords`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Article_has_Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Article_has_Keywords` (
  `Article_article_id` VARCHAR(45) NOT NULL,
  `Article_Journal_idJournal` INT NOT NULL,
  `Keywords_idKeywords` INT NOT NULL,
  PRIMARY KEY (`Article_article_id`, `Article_Journal_idJournal`, `Keywords_idKeywords`),
  INDEX `fk_Article_has_Keywords_Keywords1_idx` (`Keywords_idKeywords` ASC),
  INDEX `fk_Article_has_Keywords_Article1_idx` (`Article_article_id` ASC, `Article_Journal_idJournal` ASC),
  CONSTRAINT `fk_Article_has_Keywords_Article1`
    FOREIGN KEY (`Article_article_id` , `Article_Journal_idJournal`)
    REFERENCES `mydb`.`Article` (`article_id` , `Journal_idJournal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_has_Keywords_Keywords1`
    FOREIGN KEY (`Keywords_idKeywords`)
    REFERENCES `mydb`.`Keywords` (`idKeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
