-- MySQL Script generated by MySQL Workbench
-- lun 16 mar 2020 14:39:58 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema freedmetrics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema freedmetrics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freedmetrics` ;
USE `freedmetrics` ;

-- -----------------------------------------------------
-- Table `freedmetrics`.`Persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Persons` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `last_connection` VARCHAR(45) NULL DEFAULT NULL,
  `num_articles_searched` INT NULL DEFAULT NULL,
  `field` VARCHAR(45) NULL DEFAULT NULL,
  `is_developer` TINYINT(1) NULL DEFAULT NULL,
  `vkey` VARCHAR(45) NULL DEFAULT NULL,
  `is_verified` TINYINT(1) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `fpkey` VARCHAR(45) NULL,
  `register_date` VARCHAR(45) NULL,
  FULLTEXT (name),
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Journal` (
  `automatic_id_journal` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  FULLTEXT (Name),
  PRIMARY KEY (`automatic_id_journal`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`Web_Statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Web_Statistics` (
  `idWeb_Statistics` INT NOT NULL,
  `num_searches` INT NULL DEFAULT NULL,
  `num_users` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idWeb_Statistics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`source` (
  `idsource` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsource`),
  UNIQUE INDEX `source_UNIQUE` (`source` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Article` (
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `abstract` TEXT(2000) NULL DEFAULT NULL,
  `article_date` VARCHAR(45) NULL DEFAULT NULL,
  `last_search_date` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `doi` VARCHAR(45) NULL DEFAULT NULL,
  `source_id` VARCHAR(45) NULL DEFAULT NULL,
  `wikipedia_references` INT NULL DEFAULT NULL,
  `crossref_references` INT NULL DEFAULT NULL,
  `pubmed_citations` INT NULL DEFAULT NULL,
  `total_tweets` INT NULL DEFAULT NULL,
  `original_tweets` INT NULL DEFAULT NULL,
  `visits` INT NULL DEFAULT 1,
  `source_idsource` INT NOT NULL,
  `Journal_automatic_id_journal` INT NOT NULL,
  PRIMARY KEY (`article_id`, `source_idsource`, `Journal_automatic_id_journal`),
  FULLTEXT (title),
  FULLTEXT (abstract),
  FULLTEXT (doi),
  FULLTEXT (source_id),
  INDEX `fk_Article_source1_idx` (`source_idsource` ASC),
  INDEX `fk_Article_Journal1_idx` (`Journal_automatic_id_journal` ASC),
  CONSTRAINT `fk_Article_source1`
    FOREIGN KEY (`source_idsource`)
    REFERENCES `freedmetrics`.`source` (`idsource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Journal1`
    FOREIGN KEY (`Journal_automatic_id_journal`)
    REFERENCES `freedmetrics`.`Journal` (`automatic_id_journal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`Persons_has_Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Persons_has_Article` (
  `is_user` TINYINT(1) NULL DEFAULT NULL,
  `is_author` TINYINT(1) NULL DEFAULT NULL,
  `Article_article_id` INT NOT NULL,
  `Persons_person_id` INT NOT NULL,
  PRIMARY KEY (`Article_article_id`, `Persons_person_id`),
  INDEX `fk_Persons_has_Article_Persons1_idx` (`Persons_person_id` ASC),
  CONSTRAINT `fk_Persons_has_Article_Article1`
    FOREIGN KEY (`Article_article_id`)
    REFERENCES `freedmetrics`.`Article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persons_has_Article_Persons1`
    FOREIGN KEY (`Persons_person_id`)
    REFERENCES `freedmetrics`.`Persons` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`Tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Tweet` (
  `tweet_id` INT NOT NULL,
  `Article_article_id` INT NOT NULL,
  PRIMARY KEY (`tweet_id`, `Article_article_id`),
  INDEX `fk_Tweet_Article1_idx` (`Article_article_id` ASC),
  CONSTRAINT `fk_Tweet_Article1`
    FOREIGN KEY (`Article_article_id`)
    REFERENCES `freedmetrics`.`Article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Keywords` (
  `idKeywords` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idKeywords`),
  FULLTEXT (keyword),
  UNIQUE INDEX `keyword_UNIQUE` (`keyword` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedmetrics`.`Article_has_Keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedmetrics`.`Article_has_Keywords` (
  `Article_article_id` INT NOT NULL,
  `Keywords_idKeywords` INT NOT NULL,
  PRIMARY KEY (`Article_article_id`, `Keywords_idKeywords`),
  INDEX `fk_Article_has_Keywords_Keywords2_idx` (`Keywords_idKeywords` ASC),
  CONSTRAINT `fk_Article_has_Keywords_Article2`
    FOREIGN KEY (`Article_article_id`)
    REFERENCES `freedmetrics`.`Article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_has_Keywords_Keywords2`
    FOREIGN KEY (`Keywords_idKeywords`)
    REFERENCES `freedmetrics`.`Keywords` (`idKeywords`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;